version: '2'
services:
  sling:
    image: apachesling/sling:8
    ports:
     - "8080:8080"
    links:
     - mongo:mongo
     - elasticsearch
    environment:
     - SLING_OPTS=-Dsling.run.modes=oak_mongo -Doak.mongo.uri=mongodb://mongo:27017
  mongo:
    image: mongo:3.0
  elasticsearch:
    image: elasticsearch:2.2
    ports:
     - "9200:9200"
     - "9300:9300"
  logstash:
    image: logstash:2.2
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    links:
      - elasticsearch:elasticsearch
  kibana:
    image: kibana:4.4
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
